
/*
Step 3:
  - This file defines all of the actual state functions,
  - and the state machine function that selects the active state based on the active smState variable


  - Biggest modification from previous version
  - back to using the function structure topology, however this requires that every state is passed stateData, even if that state does not use any values from it
  - suggest having a null line in each function that reads some variable from stateData just to shut up compiler warnings about unused variables.

 Imogen Heard 08/01/2026

*/




#ifndef stateMachine_h
#define stateMachine_h




// moved again
stateDef_t smState = STATE_INIT;
stateDef_t lastState;




// 4. Define the state machine function prototypes.
//    Any function that will be passed data from a user input will be passed the same jsonStateData_t structure as an argument.
// make sure every state named in step one has a prototype here!

// Required States
void sm_state_null(jsonStateData_t &stateData);
void sm_state_init(jsonStateData_t &stateData);
void sm_state_wait(jsonStateData_t &stateData);
// Experiment Specific States
void sm_state_light(jsonStateData_t &stateData);
void sm_state_hz(jsonStateData_t &stateData);
void sm_state_amp(jsonStateData_t &stateData);
void sm_state_start(jsonStateData_t &stateData);
void sm_state_stop(jsonStateData_t &stateData);
void sm_state_pulse(jsonStateData_t &stateData);
void sm_state_pumpout(jsonStateData_t &stateData);
void sm_state_pumpin(jsonStateData_t &stateData);
void sm_state_stoppump(jsonStateData_t &stateData);

// Common & Utility States
void sm_state_samplerate(jsonStateData_t &stateData);
void sm_state_printrate(jsonStateData_t &stateData);
void sm_state_start_stream(jsonStateData_t &stateData);
void sm_state_stop_stream(jsonStateData_t &stateData);
void sm_state_set_secret(jsonStateData_t &stateData);
void sm_state_reset(jsonStateData_t &stateData);
void sm_state_info(jsonStateData_t &stateData);
void sm_state_help(jsonStateData_t &stateData);

// After finishing this list -> try running https://github.com/ImogenWren/json-state-machine/blob/main/state-machine-generator.py script to auto generate
// the StateMachine[] array, and template functions for each state!





typedef struct {
  stateDef_t State;                          //< Defines thestate enum
  void (*func)(jsonStateData_t &stateData);  //< Defines the function to run
} StateMachine_t;


// Step 5 A table that defines the valid states of the state machine and the state which is called by that state keyword

// array of struct
StateMachine_t StateMachine[] = {
  { STATE_NULL, sm_state_null },
  { STATE_INIT, sm_state_init },
  { STATE_WAIT, sm_state_wait },
  { STATE_LIGHT, sm_state_light },
  { STATE_HZ, sm_state_hz },
  { STATE_AMP, sm_state_amp },
  { STATE_START, sm_state_start },
  { STATE_STOP, sm_state_stop },
  { STATE_PULSE, sm_state_pulse },
  { STATE_PUMPOUT, sm_state_pumpout },
  { STATE_PUMPIN, sm_state_pumpin },
  { STATE_STOP_PUMP, sm_state_stoppump },
  { STATE_SAMPLERATE, sm_state_samplerate },
  { STATE_PRINTRATE, sm_state_printrate },
  { STATE_STARTSTREAM, sm_state_start_stream },
  { STATE_STOPSTREAM, sm_state_stop_stream },
  { STATE_SETSECRET, sm_state_set_secret },
  { STATE_RESET, sm_state_reset },
  { STATE_INFO, sm_state_info },
  { STATE_HELP, sm_state_help },
};


// Step 5 -> Define the states themselves, have you autogenerated the templates?
#include "states.h"





// 6. Finally define the state machine function
void sm_Run(jsonStateData_t &stateData) {
  if (smState < NUM_STATES) {
#if DEBUG_STATE_MACHINE == true
    if (lastState != smState) {
      char buffer[14];
      Serial.print(F("{\"sm\":\""));
      strcpy_P(buffer, (char *)pgm_read_ptr(&(stateNames[smState])));  // Necessary casts and dereferencing, just copy.
      Serial.print(buffer);
      //  Serial.print(stateNames[smState]);   // old RAM heavy version
      Serial.println(F("\"}"));
    }
#endif
    (*StateMachine[smState].func)(stateData);

  } else {
    sm_state_wait(stateData);
    Serial.println(F("sm: Exception -> NUM_STATES exceeded"));
  }
}


#endif
